FROM arm32v7/node:9.0.0

ENV NODE_ENV production

RUN mkdir app

WORKDIR app

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json

RUN npm i

COPY ./src ./src

ENTRYPOINT [ "node", "./src/app.js" ]